### ISSUE TITLE
should we async await the hook?

### ISSUE THREAD

**Issue by lindamacdonald** [MattieBelt/strapi-hook-algolia#10]
<!--
Hello 👋 this isn't really a bug report more a question :) should we use async await with this hook to keep the search results performant?

thanks in advance
Linda

**Comment by MattieBelt** [comment]
Hey @lindamacdonald,

The services aren't `async` functions so you can't use `await` on then. Do you have a use case where you want to call on them asynchronously?

**Comment by MattieBelt** [comment]
Closed due to inactivity.
