### ISSUE TITLE
No prefix option

### ISSUE THREAD

**Issue by kanrio** [MattieBelt/strapi-hook-algolia#11]
Hey,

### Prefix Option/Parameter

Don't you think, there should be a no prefix option

### Results
`ALGOLIA_PREFIX` not declared in env file, the result of no prefix is "environment_index"  
`ALGOLIA_PREFIX=` the result of empty prefix is "_index" which is annoying

I can make a pull request for it, if you agree
Thank you

**Comment by MattieBelt** [comment]
Hey @anouarkacem, I do agree that the `_` should indeed be part of the default prefix and so can be overwritten if given an empty string, e.g.`prefix: ''`.
However this would be a breaking change which I don't wat to introduce as of right now, with Strapi V4 close by.

I think the best solution is to remove the prefix from the indexName if the `prefix` is set to `false`. 
Feel free to submit an PR for that. 👍🏼 

(_In the concept design of my new search plugin, only v4 support, I have included the `_` in the default prefix. 
https://strapi-plugin-search.mattiebelt.com/strapi-plugin-search#configuration_ )

Also checkout the recommendation from Algolia on how to handle multiple environments:
> There are two ways to split your search implementation for each environment:
> 1. Separate your environments into different indices on the same app
> 2. Create several apps, and use one per environment

https://www.algolia.com/doc/guides/sending-and-managing-data/manage-environments/#all-environments-on-the-same-application

Currently this hook only supports the first option. 👍🏼

**Comment by kanrio** [comment]
Hey @MattieBelt ,

Thank you for assigning the task to me,
I'll work on it whenever I have time, till weekend

**Comment by MattieBelt** [comment]
@anouarkacem, great! 🚀
