### ISSUE TITLE
v4 support ?

### ISSUE THREAD

**Issue by stefansdev** [MattieBelt/strapi-hook-algolia#13]
Hi,

I know that Strapi v4 has been just released, but is there a plan to update this for v4 anytime soon ?

Thanks!

**Comment by MattieBelt** [comment]
Hi @stefansdev, yes totally. I already have been working on a generic search plugin with a Algolia provider to start with.
I have been unable to finish yet, but I will publish an stable-ish beta version that will work with the `v4` asap.

You can checkout this conceptual design/documentation or this example for the `beta.0` (did not test/upgrade yet) for now. 
https://strapi-plugin-search.mattiebelt.com/
https://www.npmjs.com/package/@mattie-bundle/strapi-plugin-search (still alpha/partly undocumented)

**Comment by stefansdev** [comment]
@MattieBelt Awesome, thanks, looking forward to it.

**Comment by elchiconube** [comment]
I just start with Strapi and I would like to use Algolia for it. I'll be waiting for your docs. 

Would be awesome if you add a full example. I don't understand well where to add the code. Could you be more explicit on the Usage section? 

Thanks for your work @MattieBelt

**Comment by MattieBelt** [comment]
Hey @stefansdev, I have been testing the search plugin for `v4`, you can checkout the latest release here: [`1.0.0-alpha.2`](https://github.com/MattieBelt/mattie-strapi-bundle/releases/tag/1.0.0-alpha.2).

@elchiconube I have added a [detailed quick start guide](https://mattie-strapi-bundle-5xgi50y0l-mattiebelt.vercel.app/quick-start#search-plugin-with-algolia-provider) to the docs, let me know if this helps. Feel free to [open an issue](https://github.com/MattieBelt/mattie-strapi-bundle/issues) if you run into any problems. Next I'll be working on a GUI, so the setup and configuration is even easier to do.

_Please do note that it is still in alpha testing an is open to breaking changes in any version. The release changelogs will mention of any breaking changes._
