### ISSUE TITLE
[Suggestion/Question]: Remove toUpperCase()?

### ISSUE THREAD

**Issue by meck93** [MattieBelt/strapi-hook-algolia#2]
Hi @MattieBelt 

Thanks for the great work with the project. 

Could we remove the `toUpperCase()`? This would allow to use lower or mixed case indexes. Thanks for the feedback. I can also open a pull request to change it if you agree. 

```diff
const initIndex = (indexName) => {
---    return client.initIndex(`${prefix}_${indexName.toUpperCase()}`);
+++    return client.initIndex(`${prefix}_${indexName}`);
};
```
**Code:** https://github.com/MattieBelt/strapi-hook-algolia/blob/master/lib/index.js#L36-L38

**Comment by MattieBelt** [comment]
Hey @meck93 thanks for looking into the hook. 

I'm not sure why I'd used the `toUpperCase()`, if I'm correct [the docs](https://www.algolia.com/doc/guides/sending-and-managing-data/manage-environments/) used the env and the index in all caps as example, but as far as I can see now all lower case is just fine.

Yes feel free to open a pull request, I will release with the next Strapi release.

**Comment by meck93** [comment]
Cool, thanks a lot! Will do!
