### ISSUE TITLE
Error: Cannot find module 'strapi-hook-algolia'

### ISSUE THREAD

**Issue by valentin-harrang** [MattieBelt/strapi-hook-algolia#9]
**Describe the bug**
Hi,

I added `./config/hook.js` file with informations like this: https://github.com/MattieBelt/strapi-hook-algolia#hook-config and I executed this command to install the lib:

`npm install strapi-hook-algolia --save `

But when I get this error when I execute `strapi develop`:

> strapi_ns     | > strapi develop
> strapi_ns     | 
> strapi_ns     | [2021-05-24T19:02:33.434Z] debug ⛔️ Server wasn't able to start properly.
> strapi_ns     | [2021-05-24T19:02:33.436Z] error Error: Cannot find module 'strapi-hook-algolia'
> strapi_ns     | Require stack:
> strapi_ns     | - /srv/app/node_modules/strapi/lib/core/load-hooks.js
> strapi_ns     | - /srv/app/node_modules/strapi/lib/core/load-modules.js
> strapi_ns     | - /srv/app/node_modules/strapi/lib/Strapi.js
> strapi_ns     | - /srv/app/node_modules/strapi/lib/index.js
> strapi_ns     | - /srv/app/node_modules/strapi/lib/commands/develop.js
> strapi_ns     | - /srv/app/node_modules/strapi/bin/strapi.js
> strapi_ns     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
> strapi_ns     |     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
> strapi_ns     |     at loadHookDependencies (/srv/app/node_modules/strapi/lib/core/load-hooks.js:80:42)
> strapi_ns     |     at module.exports (/srv/app/node_modules/strapi/lib/core/load-hooks.js:17:5)
> strapi_ns     |     at module.exports (/srv/app/node_modules/strapi/lib/core/load-modules.js:29:5)
> strapi_ns     |     at Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:329:27)
> strapi_ns     |     at Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:20)
> strapi_ns     |     at module.exports (/srv/app/node_modules/strapi/lib/commands/develop.js:95:29)
> strapi_ns     |     at /srv/app/node_modules/strapi/bin/strapi.js:50:14
> strapi_ns     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> strapi_ns     | npm ERR! code ELIFECYCLE
> strapi_ns     | npm ERR! errno 1

**System**
- Node.js version: v12.18.2
- NPM version: 7.12.0
- Strapi version: 3.6.2
- Algolia hook version: 3.6.0
- Operating system: Ubuntu

**Comment by MattieBelt** [comment]
Hi @ElGecko76,

I assume you fixed it. 
Can you explain in short what you did to fix the problem? This so others with the same problem are quickly helped 😉:+1:

**Comment by valentin-harrang** [comment]
Yes sorry, I use Docker and the volume was incorrectly mounted 😅
